"""obligation model

Revision ID: 7cbe15c6512d
Revises: 
Create Date: 2026-06-26 15:15:52.482588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7cbe15c6512d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obligations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('annual_report', 'franchise_tax', 'boi_report', 'registered_agent_renewal', name='obligationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'submitted', 'done', name='obligationstatus'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('requires_document', sa.Boolean(), nullable=False),
    sa.Column('document_path', sa.String(length=512), nullable=True),
    sa.Column('company_tax_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obligations_id'), 'obligations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_obligations_id'), table_name='obligations')
    op.drop_table('obligations')
    # ### end Alembic commands ###
